# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text=b'Nome que descreva o contato', max_length=128)),
                ('canal', models.CharField(choices=[(b'email', b'E-Mail'), (b'celular', b'Celular'), (b'fixo', b'Fixo')], help_text=b'Tipo de canal de contato, podendo ser email, celular ou fixo', max_length=10)),
                ('valor', models.CharField(help_text=b'Valor para o canal de contato', max_length=254)),
                ('obs', models.CharField(blank=True, help_text=b'Qualquer observa\xc3\xa7\xc3\xa3o que seja pertinente', max_length=254, null=True)),
            ],
        ),
    ]
